syntax = "proto3";

package room_manager;

option go_package = "pkg/shared/proto/room_manager";

message UserInfo {
  string username = 1;
  uint32 team = 2;
  uint32 spell1 = 3;
  uint32 spell2 = 4;
}

service RoomService {
  rpc LookRoom(LookRoomRequest) returns (LookRoomResponse);
  //rpc UpdateSpell(UpdateSpellRequest) returns (UpdateSpellResponse);
  //rpc RoomDone(RoomDoneRequest) returns (RoomDoneResponse);
  //rpc QuitRoom(QuitRoomRequest) returns (QuitRoomResponse);
  //rpc RoomInfo(RoomInfoRequest) returns (RoomInfoResponse);
}

// --- LookRoomService
message LookRoomRequest {
  string username = 1;
  uint32 roomType = 2;
}

message LookRoomResponse {
 uint32 roomID = 1;
 uint32 team = 3;
}

// --- UpdatedSpellServce ---
message UpdateSpellRequest {
  string username = 1;
  uint32 spell1 = 2;
  uint32 spell2 = 3;
}

message UpdateSpellResponse { bool succes = 1; }

// --- RoomDoneService ---
message RoomDoneRequest {
  string username = 1;
  uint32 roomID = 2;
}

message RoomDoneResponse { bool succes = 1; }

// --- QuitRoomService ---
message QuitRoomRequest {
  string username = 1;
  uint32 roomID = 2;
}

message QuitRoomResponse { bool success = 1; }

// --- RoomInfoService ---
message RoomInfoRequest { uint32 roomID = 1; }

message RoomInfoResponse { repeated UserInfo users = 1; }
