[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
rand = "0.9.0"
byteorder = "1.5"
bytes = "1"
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "client"
path = "src/client.rs"
