[[spell]]
id = 0
mana_cost = 20
cooldown_secs = 10
range = 10
width = 5
speed = 1
base_damage = 10
damage_ratio = 0.2
stun_duration = 1

[[spell]]
id = 1
mana_cost = 10
cooldown_secs = 4
range = 6
width = 1
speed = 1
base_damage = 5
damage_ratio = 0.4

[[spell]]
id = 2
mana_cost = 40
cooldown_secs = 15
range = 8
width = 3
speed = 1
base_damage = 50
damage_ratio = 0.3
is_heal = true