[base]
health = 5000
armor = 10

[champion]
attack_damage = 20
attack_speed_ms = 2500
health = 200
mana = 100
armor = 5
xp_per_level = [35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115] # Max level 18, so 17 levels to define XP for
level_up_health_increase = 20
level_up_attack_damage_increase = 5
level_up_armor_increase = 2
attack_range_row = 3
attack_range_col = 3

[minion]
attack_damage = 6
attack_speed_ms = 2500
health = 40
armor = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3

[tower]
attack_damage = 40
attack_speed_secs = 3
health = 400
armor = 8
attack_range_row = 7
attack_range_col = 9

[[neutral_monsters]]
id = "wolf_blue"
spawn_row = 126
spawn_col = 49
attack_damage = 8
attack_speed_ms = 2000
health = 40
armor = 5
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 50
gold_reward = 75
respawn_timer_secs = 90

[[neutral_monsters]]
id = "wolf_red"
spawn_row = 49
spawn_col = 126
attack_damage = 8
attack_speed_ms = 2000
health = 40
armor = 5
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 50
gold_reward = 75
respawn_timer_secs = 90

[[neutral_monsters]]
id = "golem_blue"
spawn_row = 173 
spawn_col = 110
attack_damage = 15
attack_speed_ms = 3500
health = 40
armor = 5
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 50
gold_reward = 75
respawn_timer_secs = 90

[[neutral_monsters]]
id = "golem_red"
spawn_row = 110
spawn_col = 173
attack_damage = 15
attack_speed_ms = 3500
health = 40
armor = 5
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 50
gold_reward = 75
respawn_timer_secs = 90
