[base]
health = 2000
armor = 10

[champion]
attack_damage = 10
attack_speed_ms = 2200
health = 200
mana = 100
armor = 5
xp_per_level = [35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115] # Max level 18, so 17 levels to define XP for
level_up_health_increase = 20
level_up_attack_damage_increase = 5
level_up_armor_increase = 2
health_per_sec = 0.0025
mana_per_sec = 0.0025
attack_range_row = 3
attack_range_col = 3

[minion]
attack_damage = 9
attack_speed_ms = 2500
health = 60
armor = 0
aggro_range_row = 10
aggro_range_col = 12
attack_range_row = 3
attack_range_col = 3

[tower]
attack_damage = 40
attack_speed_secs = 3
health = 500
armor = 10
attack_range_row = 7
attack_range_col = 9

[[neutral_monsters]]
id = "wolf_blue"
spawn_row = 91
spawn_col = 30
attack_damage = 8
attack_speed_ms = 2000
health = 150
armor = 10
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "wolf_red"
spawn_row = 60
spawn_col = 119
attack_damage = 8
attack_speed_ms = 2000
health = 150
armor = 10
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "golem_blue"
spawn_row = 135 
spawn_col = 95
attack_damage = 15
attack_speed_ms = 3500
health = 150
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "golem_red"
spawn_row = 16
spawn_col = 154
attack_damage = 15
attack_speed_ms = 3500
health = 150
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "red_buff_blue"
spawn_row = 118
spawn_col = 79
attack_damage = 12
attack_speed_ms = 3000
health = 175
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "health_regen"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "red_buff_red"
spawn_row = 33
spawn_col = 70
attack_damage = 12
attack_speed_ms = 3000
health = 175
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "health_regen"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "corbin_blue"
spawn_row = 90
spawn_col = 71
attack_damage = 4
attack_speed_ms = 1500
health = 125
armor = 6
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "corbin_red"
spawn_row = 60
spawn_col = 78
attack_damage = 4
attack_speed_ms = 1500
health = 125
armor = 6
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "blue_buff_blue"
spawn_row = 65
spawn_col = 34
attack_damage = 4
attack_speed_ms = 2200
health = 160
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "mana_regen"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "blue_buff_red"
spawn_row = 83
spawn_col = 115
attack_damage = 4
attack_speed_ms = 2200
health = 160
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "mana_regen"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "frog_blue"
spawn_row = 60
spawn_col = 12
attack_damage = 7
attack_speed_ms = 2000
health = 120
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "frog_red"
spawn_row = 89
spawn_col = 136
attack_damage = 7
attack_speed_ms = 2000
health = 120
armor = 8
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90
