# In game/items.toml

[[items]]
id = 1
name = "Simple Sword"
cost = 350
stats.attack_damage = 10

[[items]]
id = 2
name = "Tome of Power"
cost = 450
stats.magic_power = 10

[[items]]
id = 3
name = "Leather Armor"
cost = 300
stats.armor = 10

[[items]]
id = 4
name = "Health Stone"
cost = 400
stats.health = 50

[[items]]
id = 5
name = "Mana Pendant"
cost = 400
stats.mana = 25

[[items]]
id = 6
name = "Dagger"
cost = 200
stats.attack_speed = 200

[[items]]
id = 7
name = "Vial of Renewal"
cost = 150
stats.health_regen = 1.0
stats.buffs = ["health_regen_item"]
stats.effects = [1.0]

[[items]]
id = 8
name = "Shield of Valor"
cost = 800
crafting_cost = 200
required = [3, 4]
stats.armor = 15
stats.health = 80

[[items]]
id = 9
name = "Double-edged Sword"
cost = 800
crafting_cost = 100
required = [1, 1]
stats.attack_damage = 25

[[items]]
id = 10
name = "Thorn Armor"
cost = 700
crafting_cost = 100
required = [3, 3]
stats.armor = 20
stats.buffs = ["thorn_item"]
stats.effects = [10.0]
