# freeze_wall
[[spell]]
id = 0
mana_cost = 20
cooldown_secs = 10
range = 10
width = 5
speed = 1
base_attack_damage = 0
base_magic_damage = 10
damage_ratio = 0
magic_ratio = 0.2
effect_duration = 1

# fireball
[[spell]]
id = 1
mana_cost = 10
cooldown_secs = 4
range = 6
width = 1
speed = 1
base_attack_damage = 0
base_magic_damage = 5
damage_ratio = 0.0
magic_ratio = 0.4

# healing_wave
[[spell]]
id = 2
mana_cost = 40
cooldown_secs = 15
range = 8
width = 3
speed = 1
base_attack_damage = 0
base_magic_damage = 50
damage_ratio = 0.0
magic_ratio = 0.3
is_heal = true

# whirlwind
[[spell]]
id = 3
mana_cost = 10
cooldown_secs = 10
range = 1
width = 1
speed = 1
base_attack_damage = 10
base_magic_damage = 0
damage_ratio = 0.3
magic_ratio = 0

# pierce
[[spell]]
id = 4
mana_cost = 5
cooldown_secs = 10
range = 1
width = 1
speed = 1
base_attack_damage = 0
base_magic_damage = 0
damage_ratio = 0.1
magic_ratio = 0
effect_duration = 5

# electric_pulse
[[spell]]
id = 5
mana_cost = 15
cooldown_secs = 8
range = 10
width = 1
speed = 1
base_attack_damage = 0
base_magic_damage = 0
damage_ratio = 0
magic_ratio = 0
cast_time_ms = 500
