[base]
health = 4000
armor = 30
magic_resistance = 0

[champion]
attack_damage = 20
attack_speed_ms = 2200
magic_power = 0
health = 400
mana = 100
armor = 20
magic_resistance = 0
xp_per_level = [35, 43, 53, 65, 79, 95, 113, 133, 155, 179, 205, 233, 263, 295, 329, 365, 403] # Max level 18, so 17 levels to define XP for
level_up_health_increase = 50
level_up_attack_damage_increase = 5
level_up_armor_increase = 3
health_per_sec = 0.0025
mana_per_sec = 0.0025
attack_range_row = 3
attack_range_col = 3

[minion]
attack_damage = 18
attack_speed_ms = 2000
health = 160
armor = 0
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 12
attack_range_row = 3
attack_range_col = 3

[tower]
attack_damage = 80
attack_speed_secs = 3
health = 900
armor = 40
magic_resistance = 0
attack_range_row = 9
attack_range_col = 12

[[neutral_monsters]]
id = "wolf_blue"
spawn_row = 91
spawn_col = 30
attack_damage = 8
attack_speed_ms = 2000
health = 170
armor = 14
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "wolf_red"
spawn_row = 60
spawn_col = 119
attack_damage = 8
attack_speed_ms = 2000
health = 170
armor = 14
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "golem_blue"
spawn_row = 135 
spawn_col = 95
attack_damage = 30
attack_speed_ms = 3500
health = 200
armor = 20
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "golem_red"
spawn_row = 16
spawn_col = 154
attack_damage = 30
attack_speed_ms = 3500
health = 200
armor = 20
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "red_buff_blue"
spawn_row = 118
spawn_col = 79
attack_damage = 30
attack_speed_ms = 3000
health = 250
armor = 22
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "red_buff"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "red_buff_red"
spawn_row = 33
spawn_col = 70
attack_damage = 30
attack_speed_ms = 3000
health = 250
armor = 22
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "red_buff"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "corbin_blue"
spawn_row = 90
spawn_col = 71
attack_damage = 16
attack_speed_ms = 1500
health = 165
armor = 6
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "corbin_red"
spawn_row = 60
spawn_col = 78
attack_damage = 16
attack_speed_ms = 1500
health = 165
armor = 6
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 15
gold_reward = 50
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "blue_buff_blue"
spawn_row = 65
spawn_col = 34
attack_damage = 30
attack_speed_ms = 3000
health = 250
armor = 22
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "blue_buff"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "blue_buff_red"
spawn_row = 83
spawn_col = 115
attack_damage = 30
attack_speed_ms = 3000
health = 250
armor = 22
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 25
gold_reward = 150
health_reward = 30
buff_reward = "blue_buff"
respawn_timer_secs = 180

[[neutral_monsters]]
id = "frog_blue"
spawn_row = 60
spawn_col = 12
attack_damage = 20
attack_speed_ms = 2000
health = 200
armor = 15
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90

[[neutral_monsters]]
id = "frog_red"
spawn_row = 89
spawn_col = 136
attack_damage = 20
attack_speed_ms = 2000
health = 200
armor = 15
magic_resistance = 0
aggro_range_row = 10
aggro_range_col = 10
attack_range_row = 3
attack_range_col = 3
leash_range = 20
xp_reward = 20
gold_reward = 75
health_reward = 30
respawn_timer_secs = 90
