// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMessageRequest) Reset() {
	*x = RouteMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMessageRequest) ProtoMessage() {}

func (x *RouteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMessageRequest.ProtoReflect.Descriptor instead.
func (*RouteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *RouteMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *RouteMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RouteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receivers     []string               `protobuf:"bytes,1,rep,name=receivers,proto3" json:"receivers,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMessageResponse) Reset() {
	*x = RouteMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMessageResponse) ProtoMessage() {}

func (x *RouteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMessageResponse.ProtoReflect.Descriptor instead.
func (*RouteMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *RouteMessageResponse) GetReceivers() []string {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *RouteMessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RegisterClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	mi := &file_proto_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterClientRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *RegisterClientRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RegisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_proto_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnregisterClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterClientRequest) Reset() {
	*x = UnregisterClientRequest{}
	mi := &file_proto_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterClientRequest) ProtoMessage() {}

func (x *UnregisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterClientRequest.ProtoReflect.Descriptor instead.
func (*UnregisterClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterClientRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type UnregisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterClientResponse) Reset() {
	*x = UnregisterClientResponse{}
	mi := &file_proto_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterClientResponse) ProtoMessage() {}

func (x *UnregisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterClientResponse.ProtoReflect.Descriptor instead.
func (*UnregisterClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_message_message_proto protoreflect.FileDescriptor

const file_proto_message_message_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message/message.proto\x12\amessage\"G\n" +
	"\x13RouteMessageRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"N\n" +
	"\x14RouteMessageResponse\x12\x1c\n" +
	"\treceivers\x18\x01 \x03(\tR\treceivers\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"H\n" +
	"\x15RegisterClientRequest\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"2\n" +
	"\x16RegisterClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x17UnregisterClientRequest\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\"4\n" +
	"\x18UnregisterClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8f\x02\n" +
	"\x0eMessageService\x12M\n" +
	"\fRouteMessage\x12\x1c.message.RouteMessageRequest\x1a\x1d.message.RouteMessageResponse\"\x00\x12S\n" +
	"\x0eRegisterClient\x12\x1e.message.RegisterClientRequest\x1a\x1f.message.RegisterClientResponse\"\x00\x12Y\n" +
	"\x10UnregisterClient\x12 .message.UnregisterClientRequest\x1a!.message.UnregisterClientResponse\"\x00B\x16Z\x14server/proto/messageb\x06proto3"

var (
	file_proto_message_message_proto_rawDescOnce sync.Once
	file_proto_message_message_proto_rawDescData []byte
)

func file_proto_message_message_proto_rawDescGZIP() []byte {
	file_proto_message_message_proto_rawDescOnce.Do(func() {
		file_proto_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_message_proto_rawDesc), len(file_proto_message_message_proto_rawDesc)))
	})
	return file_proto_message_message_proto_rawDescData
}

var file_proto_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_message_message_proto_goTypes = []any{
	(*RouteMessageRequest)(nil),      // 0: message.RouteMessageRequest
	(*RouteMessageResponse)(nil),     // 1: message.RouteMessageResponse
	(*RegisterClientRequest)(nil),    // 2: message.RegisterClientRequest
	(*RegisterClientResponse)(nil),   // 3: message.RegisterClientResponse
	(*UnregisterClientRequest)(nil),  // 4: message.UnregisterClientRequest
	(*UnregisterClientResponse)(nil), // 5: message.UnregisterClientResponse
}
var file_proto_message_message_proto_depIdxs = []int32{
	0, // 0: message.MessageService.RouteMessage:input_type -> message.RouteMessageRequest
	2, // 1: message.MessageService.RegisterClient:input_type -> message.RegisterClientRequest
	4, // 2: message.MessageService.UnregisterClient:input_type -> message.UnregisterClientRequest
	1, // 3: message.MessageService.RouteMessage:output_type -> message.RouteMessageResponse
	3, // 4: message.MessageService.RegisterClient:output_type -> message.RegisterClientResponse
	5, // 5: message.MessageService.UnregisterClient:output_type -> message.UnregisterClientResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_message_message_proto_init() }
func file_proto_message_message_proto_init() {
	if File_proto_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_message_proto_rawDesc), len(file_proto_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_message_proto_goTypes,
		DependencyIndexes: file_proto_message_message_proto_depIdxs,
		MessageInfos:      file_proto_message_message_proto_msgTypes,
	}.Build()
	File_proto_message_message_proto = out.File
	file_proto_message_message_proto_goTypes = nil
	file_proto_message_message_proto_depIdxs = nil
}
