// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/room_managing/room.proto

package room_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Team          uint32                 `protobuf:"varint,2,opt,name=team,proto3" json:"team,omitempty"`
	Spell1        uint32                 `protobuf:"varint,3,opt,name=spell1,proto3" json:"spell1,omitempty"`
	Spell2        uint32                 `protobuf:"varint,4,opt,name=spell2,proto3" json:"spell2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetTeam() uint32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *UserInfo) GetSpell1() uint32 {
	if x != nil {
		return x.Spell1
	}
	return 0
}

func (x *UserInfo) GetSpell2() uint32 {
	if x != nil {
		return x.Spell2
	}
	return 0
}

// --- LookRoomService
type LookRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RoomType      uint32                 `protobuf:"varint,2,opt,name=roomType,proto3" json:"roomType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookRoomRequest) Reset() {
	*x = LookRoomRequest{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookRoomRequest) ProtoMessage() {}

func (x *LookRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookRoomRequest.ProtoReflect.Descriptor instead.
func (*LookRoomRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{1}
}

func (x *LookRoomRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LookRoomRequest) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

type LookRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        uint32                 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Team          uint32                 `protobuf:"varint,3,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookRoomResponse) Reset() {
	*x = LookRoomResponse{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookRoomResponse) ProtoMessage() {}

func (x *LookRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookRoomResponse.ProtoReflect.Descriptor instead.
func (*LookRoomResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{2}
}

func (x *LookRoomResponse) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *LookRoomResponse) GetTeam() uint32 {
	if x != nil {
		return x.Team
	}
	return 0
}

// --- UpdatedSpellServce ---
type UpdateSpellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Spell1        uint32                 `protobuf:"varint,2,opt,name=spell1,proto3" json:"spell1,omitempty"`
	Spell2        uint32                 `protobuf:"varint,3,opt,name=spell2,proto3" json:"spell2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpellRequest) Reset() {
	*x = UpdateSpellRequest{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpellRequest) ProtoMessage() {}

func (x *UpdateSpellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpellRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpellRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSpellRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateSpellRequest) GetSpell1() uint32 {
	if x != nil {
		return x.Spell1
	}
	return 0
}

func (x *UpdateSpellRequest) GetSpell2() uint32 {
	if x != nil {
		return x.Spell2
	}
	return 0
}

type UpdateSpellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succes        bool                   `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpellResponse) Reset() {
	*x = UpdateSpellResponse{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpellResponse) ProtoMessage() {}

func (x *UpdateSpellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpellResponse.ProtoReflect.Descriptor instead.
func (*UpdateSpellResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSpellResponse) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

// --- RoomDoneService ---
type RoomDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RoomID        uint32                 `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDoneRequest) Reset() {
	*x = RoomDoneRequest{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDoneRequest) ProtoMessage() {}

func (x *RoomDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDoneRequest.ProtoReflect.Descriptor instead.
func (*RoomDoneRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{5}
}

func (x *RoomDoneRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RoomDoneRequest) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type RoomDoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succes        bool                   `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDoneResponse) Reset() {
	*x = RoomDoneResponse{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDoneResponse) ProtoMessage() {}

func (x *RoomDoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDoneResponse.ProtoReflect.Descriptor instead.
func (*RoomDoneResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{6}
}

func (x *RoomDoneResponse) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

// --- QuitRoomService ---
type QuitRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RoomID        uint32                 `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitRoomRequest) Reset() {
	*x = QuitRoomRequest{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRoomRequest) ProtoMessage() {}

func (x *QuitRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRoomRequest.ProtoReflect.Descriptor instead.
func (*QuitRoomRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{7}
}

func (x *QuitRoomRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *QuitRoomRequest) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type QuitRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitRoomResponse) Reset() {
	*x = QuitRoomResponse{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRoomResponse) ProtoMessage() {}

func (x *QuitRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRoomResponse.ProtoReflect.Descriptor instead.
func (*QuitRoomResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{8}
}

func (x *QuitRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- RoomChangeService ---
type RoomChangeNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        uint32                 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Usernames     []string               `protobuf:"bytes,2,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomChangeNotification) Reset() {
	*x = RoomChangeNotification{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomChangeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomChangeNotification) ProtoMessage() {}

func (x *RoomChangeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomChangeNotification.ProtoReflect.Descriptor instead.
func (*RoomChangeNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{9}
}

func (x *RoomChangeNotification) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *RoomChangeNotification) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- RoomInfoService ---
type RoomInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        uint32                 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfoRequest) Reset() {
	*x = RoomInfoRequest{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoRequest) ProtoMessage() {}

func (x *RoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoRequest.ProtoReflect.Descriptor instead.
func (*RoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{11}
}

func (x *RoomInfoRequest) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type RoomInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfoResponse) Reset() {
	*x = RoomInfoResponse{}
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfoResponse) ProtoMessage() {}

func (x *RoomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_managing_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfoResponse.ProtoReflect.Descriptor instead.
func (*RoomInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_managing_room_proto_rawDescGZIP(), []int{12}
}

func (x *RoomInfoResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_pkg_proto_room_managing_room_proto protoreflect.FileDescriptor

const file_pkg_proto_room_managing_room_proto_rawDesc = "" +
	"\n" +
	"\"pkg/proto/room_managing/room.proto\x12\froom_manager\"j\n" +
	"\bUserInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04team\x18\x02 \x01(\rR\x04team\x12\x16\n" +
	"\x06spell1\x18\x03 \x01(\rR\x06spell1\x12\x16\n" +
	"\x06spell2\x18\x04 \x01(\rR\x06spell2\"I\n" +
	"\x0fLookRoomRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\broomType\x18\x02 \x01(\rR\broomType\">\n" +
	"\x10LookRoomResponse\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\rR\x06roomID\x12\x12\n" +
	"\x04team\x18\x03 \x01(\rR\x04team\"`\n" +
	"\x12UpdateSpellRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06spell1\x18\x02 \x01(\rR\x06spell1\x12\x16\n" +
	"\x06spell2\x18\x03 \x01(\rR\x06spell2\"-\n" +
	"\x13UpdateSpellResponse\x12\x16\n" +
	"\x06succes\x18\x01 \x01(\bR\x06succes\"E\n" +
	"\x0fRoomDoneRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06roomID\x18\x02 \x01(\rR\x06roomID\"*\n" +
	"\x10RoomDoneResponse\x12\x16\n" +
	"\x06succes\x18\x01 \x01(\bR\x06succes\"E\n" +
	"\x0fQuitRoomRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06roomID\x18\x02 \x01(\rR\x06roomID\",\n" +
	"\x10QuitRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x16RoomChangeNotification\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\rR\x06roomID\x12\x1c\n" +
	"\tusernames\x18\x02 \x03(\tR\tusernames\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x0fRoomInfoRequest\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\rR\x06roomID\"@\n" +
	"\x10RoomInfoResponse\x12,\n" +
	"\x05users\x18\x01 \x03(\v2\x16.room_manager.UserInfoR\x05users2\xf5\x01\n" +
	"\vRoomService\x12I\n" +
	"\bLookRoom\x12\x1d.room_manager.LookRoomRequest\x1a\x1e.room_manager.LookRoomResponse\x12I\n" +
	"\bQuitRoom\x12\x1d.room_manager.QuitRoomRequest\x1a\x1e.room_manager.QuitRoomResponse\x12P\n" +
	"\x11NotifyRoomChanges\x12\x11.room_manager.Ack\x1a$.room_manager.RoomChangeNotification(\x010\x01B\x1fZ\x1dpkg/shared/proto/room_managerb\x06proto3"

var (
	file_pkg_proto_room_managing_room_proto_rawDescOnce sync.Once
	file_pkg_proto_room_managing_room_proto_rawDescData []byte
)

func file_pkg_proto_room_managing_room_proto_rawDescGZIP() []byte {
	file_pkg_proto_room_managing_room_proto_rawDescOnce.Do(func() {
		file_pkg_proto_room_managing_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_room_managing_room_proto_rawDesc), len(file_pkg_proto_room_managing_room_proto_rawDesc)))
	})
	return file_pkg_proto_room_managing_room_proto_rawDescData
}

var file_pkg_proto_room_managing_room_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_proto_room_managing_room_proto_goTypes = []any{
	(*UserInfo)(nil),               // 0: room_manager.UserInfo
	(*LookRoomRequest)(nil),        // 1: room_manager.LookRoomRequest
	(*LookRoomResponse)(nil),       // 2: room_manager.LookRoomResponse
	(*UpdateSpellRequest)(nil),     // 3: room_manager.UpdateSpellRequest
	(*UpdateSpellResponse)(nil),    // 4: room_manager.UpdateSpellResponse
	(*RoomDoneRequest)(nil),        // 5: room_manager.RoomDoneRequest
	(*RoomDoneResponse)(nil),       // 6: room_manager.RoomDoneResponse
	(*QuitRoomRequest)(nil),        // 7: room_manager.QuitRoomRequest
	(*QuitRoomResponse)(nil),       // 8: room_manager.QuitRoomResponse
	(*RoomChangeNotification)(nil), // 9: room_manager.RoomChangeNotification
	(*Ack)(nil),                    // 10: room_manager.Ack
	(*RoomInfoRequest)(nil),        // 11: room_manager.RoomInfoRequest
	(*RoomInfoResponse)(nil),       // 12: room_manager.RoomInfoResponse
}
var file_pkg_proto_room_managing_room_proto_depIdxs = []int32{
	0,  // 0: room_manager.RoomInfoResponse.users:type_name -> room_manager.UserInfo
	1,  // 1: room_manager.RoomService.LookRoom:input_type -> room_manager.LookRoomRequest
	7,  // 2: room_manager.RoomService.QuitRoom:input_type -> room_manager.QuitRoomRequest
	10, // 3: room_manager.RoomService.NotifyRoomChanges:input_type -> room_manager.Ack
	2,  // 4: room_manager.RoomService.LookRoom:output_type -> room_manager.LookRoomResponse
	8,  // 5: room_manager.RoomService.QuitRoom:output_type -> room_manager.QuitRoomResponse
	9,  // 6: room_manager.RoomService.NotifyRoomChanges:output_type -> room_manager.RoomChangeNotification
	4,  // [4:7] is the sub-list for method output_type
	1,  // [1:4] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_room_managing_room_proto_init() }
func file_pkg_proto_room_managing_room_proto_init() {
	if File_pkg_proto_room_managing_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_room_managing_room_proto_rawDesc), len(file_pkg_proto_room_managing_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_room_managing_room_proto_goTypes,
		DependencyIndexes: file_pkg_proto_room_managing_room_proto_depIdxs,
		MessageInfos:      file_pkg_proto_room_managing_room_proto_msgTypes,
	}.Build()
	File_pkg_proto_room_managing_room_proto = out.File
	file_pkg_proto_room_managing_room_proto_goTypes = nil
	file_pkg_proto_room_managing_room_proto_depIdxs = nil
}
